environments:
  configure-vm-image:
    environment_variables:
      GIT_USER: "{{SECRET:[github][username]}}"
      PYPI_USERNAME: '{{SECRET:[configure-vm-image][username]}}'
      PYPI_PASSWORD: '{{SECRET:[configure-vm-image][password]}}'
    pipelines:
      - configure-vm-image
format_version: 10
pipelines:
  configure-vm-image:
    display_order: -1
    group: bare_metal_pypi_package
    label_template: ${COUNT}
    lock_behaviour: none
    materials:
      configure_vm_image_git:
        git: https://github.com/ucphhpc/configure-vm-image.git
        branch: main
        destination: configure-vm-image
      publish_python_git:
        git: https://github.com/rasmunk/publish-python-scripts.git
        branch: main
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
        destination: publish-python-scripts
    parameters:
      ARGS: ''
      SRC_DIRECTORY: configure-vm-image
      TEST_DIRECTORY: configure-vm-image
      PUSH_DIRECTORY: publish-python-scripts
    template: bare_metal_pypi_package
